site_name: test
site_author: test
repo_url: "https://github.com/thangckt/test_mk"
docs_dir: _docs


#####ANCHOR Theme
theme:
  name: material                        # material  materialx  readthedocs  rtd-dropdown  windmill  bootswatch
  highlightjs: true
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    # - navigation.sections
    - navigation.indexes
    # - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - content.action.edit
    - navigation.footer
    - toc.follow
    # - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky

  topbar_style: glass        # glass  primary  accent
  palette:
    scheme: slate            # default (light),  slate (dark)
    # primary: blue grey     # blue grey, indigo


#####ANCHOR Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - codehilite
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "¤" # true
      toc_depth: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#####ANCHOR Plugins
plugins:
  - search: {}
  - autorefs
  - blog:
      blog_toc: true


#####ANCHOR Site content
nav:
  - home: index.md
  - blog:
    - blog/index.md
